#To define, scale and run services on Docker platform, use this file.
#This file defines how container should behave in production
version: "3"
services:
  # Service name
  broker-rabbitmq:
    image: "rabbitmq:3.7.14-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
  api:
    build: .
    environment:
      - APP_ENV=${APP_ENV}
    ports:
      - "5000:5000"
    deploy:
      #tells to run 5 instances of service named aditya_service
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    depends_on:
      - broker-rabbitmq